//+------------------------------------------------------------------+
//| Unified_ObserverOnly_EA.mq5                                      |
//| Observer-only EA. Reads unified_observer_signal.csv. No trading. |
//+------------------------------------------------------------------+
#property strict
#property version   "1.09"
#property description "Observer-only unified bridge for XAUUSD research. No order send."

input string SignalFileName = "unified_observer_signal.csv";
input int RefreshSeconds = 60;

datetime g_last_read = 0;

string Trim(string s)
{
   StringTrimLeft(s);
   StringTrimRight(s);
   return s;
}

string GetValue(const string &keys[], const string &vals[], int n, string key, string fallback="")
{
   for(int i=0; i<n; i++)
   {
      if(keys[i] == key)
         return vals[i];
   }
   return fallback;
}

int SplitCsvLine(string line, string &out[])
{
   // Simple CSV splitter for Stage bridge CSV. Values generated by Python do not contain commas.
   return StringSplit(line, ',', out);
}

bool ReadSignal(string &keys[], string &vals[], int &n)
{
   int handle = FileOpen(SignalFileName, FILE_READ|FILE_TXT|FILE_ANSI);
   if(handle == INVALID_HANDLE)
   {
      Print("Unified observer bridge: cannot open file ", SignalFileName, " error=", GetLastError());
      return false;
   }
   string header = "";
   string row = "";
   if(!FileIsEnding(handle)) header = FileReadString(handle);
   if(!FileIsEnding(handle)) row = FileReadString(handle);
   FileClose(handle);
   if(StringLen(header) == 0 || StringLen(row) == 0)
   {
      Print("Unified observer bridge: empty header/row in ", SignalFileName);
      return false;
   }
   string hk[];
   string hv[];
   int nk = SplitCsvLine(header, hk);
   int nv = SplitCsvLine(row, hv);
   n = MathMin(nk, nv);
   ArrayResize(keys, n);
   ArrayResize(vals, n);
   for(int i=0; i<n; i++)
   {
      keys[i] = Trim(hk[i]);
      vals[i] = Trim(hv[i]);
   }
   return true;
}

string RuleLine(const string &keys[], const string &vals[], int n, string short_id)
{
   string active = GetValue(keys, vals, n, short_id + "_active", "");
   string failures = GetValue(keys, vals, n, short_id + "_failures", "");
   if(StringLen(failures) > 120)
      failures = StringSubstr(failures, 0, 117) + "...";
   return short_id + " active=" + active + " fail=" + failures;
}

void UpdateChartComment(const string &keys[], const string &vals[], int n)
{
   string text = "XAUUSD Unified Observer Only\n";
   text += "feature_date=" + GetValue(keys, vals, n, "feature_date") + "  mode=" + GetValue(keys, vals, n, "mode") + "\n";
   text += "any_signal_active=" + GetValue(keys, vals, n, "any_signal_active") + "  selected=" + GetValue(keys, vals, n, "selected_rule_id") + "\n";
   text += "execution_allowed=" + GetValue(keys, vals, n, "execution_allowed") + "  order_authorized=" + GetValue(keys, vals, n, "order_authorized") + "\n";
   text += RuleLine(keys, vals, n, "K06") + "\n";
   text += RuleLine(keys, vals, n, "K03") + "\n";
   text += RuleLine(keys, vals, n, "K07") + "\n";
   text += RuleLine(keys, vals, n, "S83_14") + "\n";
   text += RuleLine(keys, vals, n, "S83_13") + "\n";
   text += RuleLine(keys, vals, n, "C96_07") + "\n";
   text += RuleLine(keys, vals, n, "S105_03");
   Comment(text);
}

void PrintRule(const string &keys[], const string &vals[], int n, string short_id)
{
   string active = GetValue(keys, vals, n, short_id + "_active", "");
   string failures = GetValue(keys, vals, n, short_id + "_failures", "");
   Print(short_id, "_active=", active, " failures=", failures);
}

void DisplaySignal()
{
   string keys[];
   string vals[];
   int n = 0;
   if(!ReadSignal(keys, vals, n)) return;

   UpdateChartComment(keys, vals, n);

   Print("Unified observer bridge");
   Print("feature_date=", GetValue(keys, vals, n, "feature_date"));
   Print("mode=", GetValue(keys, vals, n, "mode"));
   Print("any_signal_active=", GetValue(keys, vals, n, "any_signal_active"));
   Print("selected_rule=", GetValue(keys, vals, n, "selected_rule_id"));
   Print("selected_label=", GetValue(keys, vals, n, "selected_label"));
   Print("execution_allowed=", GetValue(keys, vals, n, "execution_allowed"));
   Print("K06_primary_active=", GetValue(keys, vals, n, "primary_signal_active"), " failures=", GetValue(keys, vals, n, "primary_failures"));
   PrintRule(keys, vals, n, "K06");
   PrintRule(keys, vals, n, "K03");
   PrintRule(keys, vals, n, "K07");
   PrintRule(keys, vals, n, "S83_14");
   PrintRule(keys, vals, n, "S83_13");
   PrintRule(keys, vals, n, "C96_07");
   PrintRule(keys, vals, n, "S105_03");
}

int OnInit()
{
   EventSetTimer(RefreshSeconds);
   DisplaySignal();
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   Comment("");
   EventKillTimer();
}

void OnTimer()
{
   DisplaySignal();
}

void OnTick()
{
   // Observer-only. Intentionally no trading logic.
}
