"""
Stage32F — Extended Dense Shadow Refresh Cycle for XAUUSD.

Purpose:
- Provide a short, repeatable local command to run after each AMarkets/FRED data refresh.
- Refresh the dense forward shadow path only: Stage32C -> Stage32D -> Stage32E.
- Keep the fastest safe commercial path focused on the leading dense candidate until extended sample thresholds are met.
- Avoid adding broad research/discovery work when the current bottleneck is simply more forward-observable samples.

Inputs:
- Stage32B queue: data/reports/stage32b_dense_forward_shadow_intake/shadow_intake_queue.csv
- Stage32C/D/E artifacts generated by the modules in this cycle.

Outputs:
- data/reports/stage32f_extended_shadow_refresh_cycle/stage32f_extended_shadow_refresh_cycle.md
- data/reports/stage32f_extended_shadow_refresh_cycle/stage32f_summary.json
- data/reports/stage32f_extended_shadow_refresh_cycle/focus_status.csv/json
- data/reports/stage32f_extended_shadow_refresh_cycle/module_runs.csv/json

Safety:
- Research/shadow only.
- No EA changes.
- No paper/live.
- No order authorization.
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

ROOT = Path.cwd()
REPORT_ROOT = ROOT / "data" / "reports"
OUT_DIR = REPORT_ROOT / "stage32f_extended_shadow_refresh_cycle"

STAGE32C_DIR = REPORT_ROOT / "stage32c_dense_forward_shadow_tracker"
STAGE32D_DIR = REPORT_ROOT / "stage32d_dense_forward_review"
STAGE32E_DIR = REPORT_ROOT / "stage32e_extended_dense_shadow_monitor"

COMMERCIAL_GOAL = "FASTEST_SAFE_PATH_TO_COMMERCIALLY_USABLE_SYSTEM"


@dataclass
class ModuleRun:
    group: str
    arm: str
    module: str
    required: bool
    returncode: int
    status: str
    duration_sec: float
    stdout: str
    stderr: str


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def iso(dt: datetime) -> str:
    return dt.isoformat(timespec="seconds")


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def ensure_dirs() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)


def sanitize_md(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def read_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return {"_read_error": str(exc), "_path": rel(path)}


def read_csv(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    try:
        with path.open("r", encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))
    except UnicodeDecodeError:
        with path.open("r", encoding="utf-8-sig", newline="") as f:
            return list(csv.DictReader(f))
    except Exception as exc:
        return [{"_read_error": str(exc), "_path": rel(path)}]


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("\n", encoding="utf-8")
        return
    fields: List[str] = []
    for row in rows:
        for k in row.keys():
            if k not in fields:
                fields.append(k)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def to_int(value: Any, default: int = 0) -> int:
    try:
        if value is None or value == "":
            return default
        return int(float(str(value)))
    except Exception:
        return default


def to_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None or value == "":
            return default
        return float(str(value))
    except Exception:
        return default


def run_module(module: str, *, group: str, arm: str, required: bool, timeout_sec: int) -> ModuleRun:
    stdout_path = OUT_DIR / f"{arm}.stdout.log"
    stderr_path = OUT_DIR / f"{arm}.stderr.log"
    cmd = [sys.executable, "-m", module]
    started = time.time()
    try:
        completed = subprocess.run(
            cmd,
            cwd=ROOT,
            text=True,
            capture_output=True,
            timeout=(timeout_sec if timeout_sec and timeout_sec > 0 else None),
        )
        stdout_path.write_text(completed.stdout or "", encoding="utf-8")
        stderr_path.write_text(completed.stderr or "", encoding="utf-8")
        rc = int(completed.returncode)
        status = "ok" if rc == 0 else "error"
    except subprocess.TimeoutExpired as exc:
        stdout_path.write_text(exc.stdout or "", encoding="utf-8")
        stderr_path.write_text((exc.stderr or "") + f"\nTIMEOUT after {timeout_sec} sec\n", encoding="utf-8")
        rc = 124
        status = "timeout"
    except Exception as exc:
        stdout_path.write_text("", encoding="utf-8")
        stderr_path.write_text(str(exc) + "\n", encoding="utf-8")
        rc = 125
        status = "exception"
    return ModuleRun(
        group=group,
        arm=arm,
        module=module,
        required=required,
        returncode=rc,
        status=status,
        duration_sec=round(time.time() - started, 3),
        stdout=rel(stdout_path),
        stderr=rel(stderr_path),
    )


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the Stage32F extended dense shadow refresh cycle.")
    parser.add_argument("--run-active-wrapper", action="store_true", help="Run app.run_active_shadow_suite_with_exogenous_watchlist before Stage32C/D/E. Use after new AMarkets CSV files are in place if you want import+observation in one command.")
    parser.add_argument("--skip-stage32c", action="store_true", help="Skip Stage32C tracker refresh.")
    parser.add_argument("--skip-stage32d", action="store_true", help="Skip Stage32D review refresh.")
    parser.add_argument("--skip-stage32e", action="store_true", help="Skip Stage32E extended monitor refresh.")
    parser.add_argument("--timeout-sec", type=int, default=0, help="Optional timeout per module. 0 means no timeout.")
    parser.add_argument("--fail-on-error", action="store_true", help="Return nonzero when any required module fails.")
    return parser.parse_args(argv)


def build_focus_status() -> List[Dict[str, Any]]:
    focus_rows = read_csv(STAGE32E_DIR / "extended_shadow_focus_queue.csv")
    summary_e = read_json(STAGE32E_DIR / "stage32e_summary.json")
    summary_d = read_json(STAGE32D_DIR / "stage32d_summary.json")
    summary_c = read_json(STAGE32C_DIR / "stage32c_summary.json")
    rows: List[Dict[str, Any]] = []
    for row in focus_rows:
        candidate = row.get("candidate", "")
        role = row.get("monitor_role", "")
        signal_count = to_int(row.get("signal_count"))
        remaining = to_int(row.get("remaining_to_extended_min"))
        pf = to_float(row.get("pf_x4"))
        wr = to_float(row.get("win_rate_x4"))
        tail_pf = to_float(row.get("tail_pf_x4"))
        dd = to_float(row.get("max_drawdown_x4"))
        if role == "PRIMARY_EXTENDED_SHADOW":
            if remaining <= 0 and (summary_e.get("pre_commercial_robustness_queue_rows") or 0) > 0:
                action = "RUN_PRE_COMMERCIAL_ROBUSTNESS_GATE_NEXT"
            elif remaining <= 0:
                action = "RECHECK_STAGE32D_E_THRESHOLDS_BEFORE_ROBUSTNESS_GATE"
            else:
                action = "CONTINUE_EXTENDED_SHADOW_COLLECTION"
        elif role == "PROMISING_LOW_N_ACCELERATION":
            action = "KEEP_COLLECTING_TO_MIN_REVIEW_SAMPLE_COUNT"
        elif role == "SECONDARY_COLLECTION":
            action = "KEEP_SECONDARY_BACKGROUND_COLLECTION_ONLY"
        else:
            action = "MONITOR_ONLY"
        rows.append(
            {
                "candidate": candidate,
                "family": row.get("family", ""),
                "monitor_role": role,
                "signal_count": signal_count,
                "remaining_to_extended_min": remaining,
                "pf_x4": pf,
                "win_rate_x4": wr,
                "tail_pf_x4": tail_pf,
                "max_drawdown_x4": dd,
                "next_action": action,
                "stage32e_decision": summary_e.get("decision", ""),
                "stage32d_decision": summary_d.get("decision", ""),
                "stage32c_decision": summary_c.get("decision", ""),
            }
        )
    return rows


def decide(module_runs: List[ModuleRun], focus_status: List[Dict[str, Any]]) -> Dict[str, Any]:
    summary_e = read_json(STAGE32E_DIR / "stage32e_summary.json")
    summary_d = read_json(STAGE32D_DIR / "stage32d_summary.json")
    pre_rows = to_int(summary_e.get("pre_commercial_robustness_queue_rows"))
    leading = str(summary_e.get("leading_candidate") or "")
    remaining = to_int(summary_e.get("leading_remaining_to_extended_min"), default=999)
    required_errors = sum(1 for m in module_runs if m.required and m.returncode != 0)
    if required_errors:
        decision = "STAGE32F_REQUIRED_MODULE_ERROR_RESEARCH_SHADOW_ONLY"
        next_action = "FIX_STAGE32F_MODULE_ERRORS_BEFORE_INTERPRETING_FAST_PATH"
    elif pre_rows > 0:
        decision = "STAGE32F_PRE_COMMERCIAL_ROBUSTNESS_QUEUE_READY_RESEARCH_ONLY"
        next_action = "RUN_PRE_COMMERCIAL_ROBUSTNESS_GATE_PATCH_NEXT_NO_EA_NO_PAPER_LIVE"
    elif leading and remaining > 0:
        decision = "STAGE32F_EXTENDED_SHADOW_CONTINUE_COLLECTION_RESEARCH_ONLY"
        next_action = "REFRESH_AMARKETS_DATA_THEN_RERUN_STAGE32F_UNTIL_EXTENDED_MIN_REACHED"
    elif leading:
        decision = "STAGE32F_EXTENDED_MIN_REACHED_BUT_NOT_ROBUSTNESS_READY_RESEARCH_ONLY"
        next_action = "RERUN_STAGE32D_E_AND_INSPECT_STABILITY_THRESHOLDS"
    else:
        decision = "STAGE32F_NO_LEADING_EXTENDED_SHADOW_CANDIDATE_RESEARCH_ONLY"
        next_action = "RETURN_TO_STAGE32B_C_DENSE_INTAKE_AND_TRACKER"
    return {
        "decision": decision,
        "generated_utc": iso(utc_now()),
        "commercial_goal": COMMERCIAL_GOAL,
        "execution_status": "RESEARCH_SHADOW_ONLY",
        "no_ea_change": True,
        "no_paper_live": True,
        "no_order_authorization": True,
        "commercial_transition_authorized": False,
        "required_module_errors": required_errors,
        "module_run_count": len(module_runs),
        "leading_candidate": leading,
        "leading_remaining_to_extended_min": remaining if leading else None,
        "focus_queue_rows": len(focus_status),
        "pre_commercial_robustness_queue_rows": pre_rows,
        "extended_min_signals": summary_e.get("extended_min_signals"),
        "stage32e_decision": summary_e.get("decision"),
        "stage32d_decision": summary_d.get("decision"),
        "ledger_rows": summary_e.get("ledger_rows"),
        "next_action": next_action,
        "primary_objective": "REPEAT_FAST_PATH_AFTER_EACH_DATA_REFRESH_UNTIL_EXTENDED_SHADOW_THRESHOLDS_ARE_MET",
    }


def write_report(summary: Dict[str, Any], module_runs: List[ModuleRun], focus_status: List[Dict[str, Any]]) -> None:
    path = OUT_DIR / "stage32f_extended_shadow_refresh_cycle.md"
    lines: List[str] = []
    lines.append("# XAUUSD Stage32F — Extended Dense Shadow Refresh Cycle")
    lines.append("")
    lines.append(f"Generated UTC: {summary.get('generated_utc')}")
    lines.append("")
    lines.append("## Decision")
    lines.append("")
    lines.append("```text")
    lines.append(f"DECISION = {summary.get('decision')}")
    lines.append("EXECUTION_STATUS = RESEARCH_SHADOW_ONLY")
    lines.append("NO_EA_CHANGE = True")
    lines.append("NO_PAPER_LIVE = True")
    lines.append("NO_ORDER_AUTHORIZATION = True")
    lines.append(f"COMMERCIAL_GOAL = {COMMERCIAL_GOAL}")
    lines.append("PRIMARY_OBJECTIVE = REPEAT_FAST_PATH_AFTER_EACH_DATA_REFRESH_UNTIL_EXTENDED_SHADOW_THRESHOLDS_ARE_MET")
    lines.append("```")
    lines.append("")
    lines.append("## Why this stage exists")
    lines.append("")
    lines.append("Stage32E created an extended-shadow focus queue. Stage32F is the operational refresh cycle: after AMarkets/FRED data refresh, rerun the dense forward path only (Stage32C -> Stage32D -> Stage32E) and report whether the leading candidate is still collecting, has reached pre-commercial robustness review, or needs repair.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("```text")
    for key in [
        "decision",
        "leading_candidate",
        "leading_remaining_to_extended_min",
        "focus_queue_rows",
        "pre_commercial_robustness_queue_rows",
        "extended_min_signals",
        "ledger_rows",
        "required_module_errors",
        "next_action",
    ]:
        lines.append(f"{key} = {summary.get(key)}")
    lines.append("```")
    lines.append("")
    lines.append("## Module runs")
    lines.append("")
    lines.append("| group | arm | module | required | returncode | status | duration_sec | stdout | stderr |")
    lines.append("|---|---|---|---:|---:|---|---:|---|---|")
    if module_runs:
        for m in module_runs:
            lines.append(
                f"| {sanitize_md(m.group)} | {sanitize_md(m.arm)} | `{sanitize_md(m.module)}` | "
                f"{str(m.required).lower()} | {m.returncode} | {sanitize_md(m.status)} | {m.duration_sec} | "
                f"`{sanitize_md(m.stdout)}` | `{sanitize_md(m.stderr)}` |"
            )
    else:
        lines.append("| none | none | none | false | 0 | skipped | 0 |  |  |")
    lines.append("")
    lines.append("## Focus status")
    lines.append("")
    lines.append("| candidate | role | signals | remaining | pf_x4 | win_rate_x4 | tail_pf_x4 | max_drawdown_x4 | next_action |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---:|---|")
    if focus_status:
        for row in focus_status:
            lines.append(
                f"| {sanitize_md(row.get('candidate'))} | {sanitize_md(row.get('monitor_role'))} | "
                f"{row.get('signal_count')} | {row.get('remaining_to_extended_min')} | "
                f"{row.get('pf_x4')} | {row.get('win_rate_x4')} | {row.get('tail_pf_x4')} | "
                f"{row.get('max_drawdown_x4')} | {sanitize_md(row.get('next_action'))} |"
            )
    else:
        lines.append("| none | none | 0 |  |  |  |  |  | NO_FOCUS_QUEUE_FOUND |")
    lines.append("")
    lines.append("## Operational interpretation")
    lines.append("")
    lines.append("```text")
    lines.append("1. This is the repeat command after each AMarkets data refresh; it should not expand research unless the focus queue fails.")
    lines.append("2. Continue collecting the leading candidate until the extended sample threshold is met.")
    lines.append("3. Promising low-N candidates stay in acceleration; weak siblings remain suppressed/repair-only.")
    lines.append("4. No EA/paper/live/order transition is authorized by this stage.")
    lines.append("```")
    lines.append("")
    lines.append("## Output files")
    lines.append("")
    for p in [
        OUT_DIR / "stage32f_extended_shadow_refresh_cycle.md",
        OUT_DIR / "focus_status.csv",
        OUT_DIR / "focus_status.json",
        OUT_DIR / "module_runs.csv",
        OUT_DIR / "module_runs.json",
        OUT_DIR / "stage32f_summary.json",
    ]:
        lines.append(f"- `{rel(p)}`")
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: Optional[Sequence[str]] = None) -> int:
    ensure_dirs()
    args = parse_args(argv)
    module_runs: List[ModuleRun] = []

    if args.run_active_wrapper:
        module_runs.append(
            run_module(
                "app.run_active_shadow_suite_with_exogenous_watchlist",
                group="data_refresh_observation",
                arm="active_shadow_suite_with_exogenous_watchlist",
                required=True,
                timeout_sec=args.timeout_sec,
            )
        )
    if not args.skip_stage32c:
        module_runs.append(
            run_module(
                "app.stage32c_dense_forward_shadow_tracker",
                group="dense_forward_path",
                arm="stage32c_dense_forward_shadow_tracker",
                required=True,
                timeout_sec=args.timeout_sec,
            )
        )
    if not args.skip_stage32d:
        module_runs.append(
            run_module(
                "app.stage32d_dense_forward_review",
                group="dense_forward_path",
                arm="stage32d_dense_forward_review",
                required=True,
                timeout_sec=args.timeout_sec,
            )
        )
    if not args.skip_stage32e:
        module_runs.append(
            run_module(
                "app.stage32e_extended_dense_shadow_monitor",
                group="dense_forward_path",
                arm="stage32e_extended_dense_shadow_monitor",
                required=True,
                timeout_sec=args.timeout_sec,
            )
        )

    focus_status = build_focus_status()
    summary = decide(module_runs, focus_status)

    write_csv(OUT_DIR / "module_runs.csv", [asdict(m) for m in module_runs])
    write_json(OUT_DIR / "module_runs.json", [asdict(m) for m in module_runs])
    write_csv(OUT_DIR / "focus_status.csv", focus_status)
    write_json(OUT_DIR / "focus_status.json", focus_status)
    write_json(OUT_DIR / "stage32f_summary.json", summary)
    write_report(summary, module_runs, focus_status)

    print(summary.get("decision"))
    print(f"leading_candidate={summary.get('leading_candidate')}")
    print(f"leading_remaining_to_extended_min={summary.get('leading_remaining_to_extended_min')}")
    print(f"next_action={summary.get('next_action')}")
    print(f"report={rel(OUT_DIR / 'stage32f_extended_shadow_refresh_cycle.md')}")

    if args.fail_on_error and summary.get("required_module_errors", 0):
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
