#!/usr/bin/env python3
from __future__ import annotations

import argparse
import fnmatch
import json
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def run_git(root: Path, args: List[str]) -> Tuple[int, str, str]:
    try:
        p = subprocess.run(['git'] + args, cwd=root, text=True, capture_output=True, check=False)
        return p.returncode, p.stdout, p.stderr
    except FileNotFoundError:
        return 127, '', 'git not found'


def load_json(path: Path) -> Dict[str, Any]:
    with path.open('r', encoding='utf-8') as f:
        return json.load(f)


def write_json(path: Path, obj: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
        f.write('\n')


def gitignore_block(cfg: Dict[str, Any]) -> str:
    start = cfg['gitignore_block_marker_start']
    end = cfg['gitignore_block_marker_end']
    patterns = cfg['runtime_ignore_patterns']
    lines = [start, '# Generated by Stage101. Runtime outputs stay local; source code/config/docs/tests remain tracked.']
    lines.extend(patterns)
    lines.append(end)
    return '\n'.join(lines) + '\n'


def read_text(path: Path) -> str:
    if not path.exists():
        return ''
    return path.read_text(encoding='utf-8', errors='replace')


def append_gitignore_if_requested(root: Path, cfg: Dict[str, Any], apply: bool) -> Dict[str, Any]:
    gi = root / '.gitignore'
    text = read_text(gi)
    start = cfg['gitignore_block_marker_start']
    already = start in text
    block = gitignore_block(cfg)
    applied = False
    if apply and not already:
        with gi.open('a', encoding='utf-8') as f:
            if text and not text.endswith('\n'):
                f.write('\n')
            if text.strip():
                f.write('\n')
            f.write(block)
        applied = True
    return {'path': str(gi), 'exists': gi.exists(), 'block_present_before_apply': already, 'applied': applied, 'block': block}


def list_tracked(root: Path) -> List[str]:
    rc, out, err = run_git(root, ['ls-files'])
    if rc != 0:
        return []
    return [x.strip() for x in out.splitlines() if x.strip()]


def list_status(root: Path) -> List[str]:
    rc, out, err = run_git(root, ['status', '--short'])
    if rc != 0:
        return []
    return out.splitlines()


def is_under(path: str, rootname: str) -> bool:
    return path == rootname or path.startswith(rootname.rstrip('/') + '/')


def matches_cleanup(path: str, cfg: Dict[str, Any]) -> bool:
    for r in cfg.get('tracked_cleanup_roots', []):
        if is_under(path, r):
            return True
    for pat in cfg.get('tracked_cleanup_globs', []):
        if fnmatch.fnmatch(path, pat):
            return True
    return False


def summarize_sizes(root: Path, paths: List[str]) -> Dict[str, Any]:
    total = 0
    existing = 0
    largest = []
    for rel in paths:
        p = root / rel
        if p.is_file():
            try:
                size = p.stat().st_size
            except OSError:
                size = 0
            total += size
            existing += 1
            largest.append({'path': rel, 'size_bytes': size})
    largest.sort(key=lambda x: x['size_bytes'], reverse=True)
    return {'existing_file_count': existing, 'total_size_bytes': total, 'largest': largest[:25]}


def build_untrack_commands(candidates: List[str]) -> List[str]:
    commands = []
    # Prefer root-level commands; still safe because they are --cached only.
    roots = []
    for r in [
        'reports',
        'data/local',
        'data/mt5_bridge',
        'data/external_frontiers',
        'data/frontier_templates',
        'data/macro_regime/normalized',
        'data/macro_regime/raw',
        'data/exogenous',
    ]:
        if any(is_under(c, r) for c in candidates):
            roots.append(r)
    if roots:
        commands.append('git rm -r --cached --ignore-unmatch ' + ' '.join(roots))
    if any(c.endswith('.zip') for c in candidates):
        commands.append("git rm --cached --ignore-unmatch *.zip")
    dbs = [c for c in candidates if c.endswith(('.db', '.sqlite', '.sqlite3'))]
    if dbs:
        commands.append("git rm --cached --ignore-unmatch '*.db' '*.sqlite' '*.sqlite3'")
    return commands


def write_report(out_dir: Path, summary: Dict[str, Any]) -> Path:
    p = out_dir / 'stage101_repo_hygiene_cleanup_audit_report.md'
    gi = summary['gitignore']
    lines = []
    lines.append('# Stage101 Repo Hygiene Cleanup Audit')
    lines.append('')
    lines.append('## Decision')
    lines.append(f"- status: `{summary['status']}`")
    lines.append(f"- decision: `{summary['decision']}`")
    lines.append(f"- classification: `{summary['classification']}`")
    lines.append(f"- disposition: `{summary['disposition']}`")
    lines.append('')
    lines.append('## Gitignore')
    lines.append(f"- block_present_before_apply: `{gi['block_present_before_apply']}`")
    lines.append(f"- applied: `{gi['applied']}`")
    lines.append('')
    lines.append('## Tracked cleanup candidates')
    lines.append(f"- count: `{summary['tracked_cleanup_candidate_count']}`")
    lines.append(f"- total_size_bytes: `{summary['tracked_cleanup_size']['total_size_bytes']}`")
    lines.append('')
    if summary['suggested_untrack_commands']:
        lines.append('## Suggested safe untrack commands')
        lines.append('These commands remove runtime artifacts from git index only. They do not delete local files.')
        lines.append('```bash')
        lines.extend(summary['suggested_untrack_commands'])
        lines.append('```')
        lines.append('')
    lines.append('## Hard blocks')
    for h in summary['hard_blocks']:
        lines.append(f'- `{h}`')
    lines.append('')
    p.write_text('\n'.join(lines), encoding='utf-8')
    return p


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default='.')
    ap.add_argument('--config', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--apply-gitignore', action='store_true')
    args = ap.parse_args()

    root = Path(args.root).expanduser().resolve()
    cfg_path = Path(args.config).expanduser()
    if not cfg_path.is_absolute():
        cfg_path = (root / cfg_path).resolve()
    cfg = load_json(cfg_path)
    out_dir = Path(args.out).expanduser()
    if not out_dir.is_absolute():
        out_dir = (root / out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    git_rc, _, git_err = run_git(root, ['rev-parse', '--show-toplevel'])
    git_ok = git_rc == 0
    tracked = list_tracked(root) if git_ok else []
    status_lines = list_status(root) if git_ok else []
    candidates = [p for p in tracked if matches_cleanup(p, cfg)]
    sizes = summarize_sizes(root, candidates)
    gi_info = append_gitignore_if_requested(root, cfg, args.apply_gitignore)
    commands = build_untrack_commands(candidates)

    if not git_ok:
        status = 'STAGE101_COMPLETE_WITH_ISSUES_NO_PROMOTION'
        decision = 'GIT_REPO_NOT_DETECTED_NO_CLEANUP_APPLIED'
        classification = 'S101_GIT_NOT_READY'
        disposition = 'RUN_FROM_REPO_ROOT'
    elif candidates or not gi_info['block_present_before_apply']:
        status = 'STAGE101_COMPLETE_NO_PROMOTION'
        decision = 'STAGE101_REPO_HYGIENE_ACTIONS_READY_NO_DELETE'
        classification = 'S101_CLEANUP_ACTIONS_READY'
        disposition = 'APPLY_GITIGNORE_AND_UNTRACK_RUNTIME_ARTIFACTS'
    else:
        status = 'STAGE101_COMPLETE_NO_PROMOTION'
        decision = 'STAGE101_REPO_HYGIENE_ALREADY_CLEAN_NO_DELETE'
        classification = 'S101_ALREADY_CLEAN'
        disposition = 'NO_RUNTIME_ARTIFACTS_TRACKED'

    (out_dir / 'stage101_gitignore_append_block.txt').write_text(gi_info['block'], encoding='utf-8')
    (out_dir / 'stage101_suggested_untrack_commands.txt').write_text('\n'.join(commands) + ('\n' if commands else ''), encoding='utf-8')
    write_json(out_dir / 'stage101_tracked_cleanup_candidates.json', {'tracked_cleanup_candidates': candidates})

    summary: Dict[str, Any] = {
        'stage': cfg.get('stage', 'Stage101_REPO_HYGIENE_CLEANUP_AUDIT'),
        'root': str(root),
        'config': str(cfg_path),
        'generated_utc': utc_now(),
        'status': status,
        'decision': decision,
        'classification': classification,
        'disposition': disposition,
        'principle': 'Clean repo hygiene before further thesis discovery. Do not delete local runtime data; only ignore/untrack generated artifacts.',
        'git_ok': git_ok,
        'git_error': git_err if not git_ok else None,
        'git_status_short_count': len(status_lines),
        'git_status_short': status_lines[:200],
        'gitignore': gi_info,
        'tracked_cleanup_candidate_count': len(candidates),
        'tracked_cleanup_candidates_sample': candidates[:200],
        'tracked_cleanup_size': sizes,
        'suggested_untrack_commands': commands,
        'outputs': {
            'summary_json': str(out_dir / 'stage101_repo_hygiene_cleanup_audit_summary.json'),
            'report_md': str(out_dir / 'stage101_repo_hygiene_cleanup_audit_report.md'),
            'gitignore_append_block': str(out_dir / 'stage101_gitignore_append_block.txt'),
            'suggested_untrack_commands': str(out_dir / 'stage101_suggested_untrack_commands.txt'),
            'tracked_cleanup_candidates': str(out_dir / 'stage101_tracked_cleanup_candidates.json'),
        },
        'hard_blocks': [
            'NO_DELETE_LOCAL_DATA',
            'NO_ORDER_OR_BROKER_CHANGE',
            'NO_MT5_OR_EA_CHANGE',
            'NO_THESIS_DISCOVERY_FROM_STAGE101',
            'NO_BASH_INSTALL_SCRIPT',
        ],
    }
    write_json(out_dir / 'stage101_repo_hygiene_cleanup_audit_summary.json', summary)
    write_report(out_dir, summary)
    print(json.dumps({'status': status, 'decision': decision, 'tracked_cleanup_candidate_count': len(candidates), 'suggested_untrack_commands': commands}, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
