#!/usr/bin/env python3
"""Stage66A2 H64L reconstruction reconciler.

Purpose:
- Diagnose why Stage66A reconstructed active events do not match the locked Stage64R count.
- Do not rescue, retune, or promote. This script only reconciles rule/data definitions.
- If exactly one pre-registered variant matches the Stage64R count within tolerance, write a proposed locked rule v2 and a rerun config.

No broker connection. No orders. No threshold tuning.
"""
from __future__ import annotations

import argparse
import copy
import datetime as dt
import itertools
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

from stage66_common_h64l import (
    apply_h64l_rule,
    build_external_index,
    canonical_sha256,
    horizon_return_bps,
    load_locked_rule,
    mean,
    parse_date,
    parse_float,
    read_csv,
    read_json,
    stddev,
    write_json,
    write_report,
)


def _iso_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _cond_id(cond: Dict[str, Any]) -> str:
    return f"{cond.get('field')} {cond.get('operator')} {cond.get('threshold')}"


def _make_rule_variant(base_rule: Dict[str, Any], variant_id: str, extra_conditions: List[Dict[str, Any]]) -> Dict[str, Any]:
    payload = copy.deepcopy(base_rule["rule_lock_payload"])
    base_conditions = payload.get("conditions", [])
    existing_ids = {_cond_id(c) for c in base_conditions}
    for cond in extra_conditions:
        if _cond_id(cond) not in existing_ids:
            base_conditions.append(copy.deepcopy(cond))
    payload["conditions"] = base_conditions
    payload["version"] = variant_id
    payload["description"] = (
        "Proposed H64L locked rule variant generated by Stage66A2 reconstruction reconciler. "
        "This is not threshold tuning; it is rule-definition reconciliation against Stage64R."
    )
    return {"rule_lock_payload": payload, "rule_sha256": canonical_sha256(payload)}


def _read_rows(root: Path, cfg: Dict[str, Any]) -> Tuple[List[Dict[str, str]], List[Tuple[dt.date, float, Dict[str, str]]]]:
    macro_rows, _ = read_csv(root / cfg["macro_dataset_path"])
    external_rows, _ = read_csv(root / cfg["external_d1_path"])
    external_series = build_external_index(
        external_rows,
        cfg.get("external_date_col", "date_utc"),
        cfg.get("external_close_col", "close"),
    )
    return macro_rows, external_series


def _event_stats_for_rule(
    macro_rows: List[Dict[str, str]],
    external_series: List[Tuple[dt.date, float, Dict[str, str]]],
    rule: Dict[str, Any],
    cfg: Dict[str, Any],
) -> Dict[str, Any]:
    feature_date_col = cfg.get("feature_date_col", "feature_date_utc")
    horizon = int(cfg.get("horizon_trading_days", rule["rule_lock_payload"].get("horizon_trading_days", 120)))
    rows_sorted = sorted(
        [r for r in macro_rows if parse_date(r.get(feature_date_col)) is not None],
        key=lambda r: parse_date(r.get(feature_date_col)),
    )
    returns: List[float] = []
    active_rows = 0
    active_with_horizon = 0
    first_active: Optional[str] = None
    last_active: Optional[str] = None
    missing_horizon = 0
    year_counts: Dict[str, int] = {}
    failed_condition_counts: Dict[str, int] = {}

    for row in rows_sorted:
        active, failures = apply_h64l_rule(row, rule)
        for f in failures:
            # Keep only field/operator-ish prefix for compact diagnostics.
            key = f.split(":", 1)[0] if ":" in f else f
            failed_condition_counts[key] = failed_condition_counts.get(key, 0) + 1
        if not active:
            continue
        fd = parse_date(row.get(feature_date_col))
        if fd is None:
            continue
        active_rows += 1
        first_active = first_active or fd.isoformat()
        last_active = fd.isoformat()
        ret, start_d, end_d = horizon_return_bps(external_series, fd, horizon)
        if ret is None:
            missing_horizon += 1
            continue
        active_with_horizon += 1
        returns.append(float(ret))
        year_counts[str(fd.year)] = year_counts.get(str(fd.year), 0) + 1

    expected = int(cfg["expected_stage64r_candidate_active_days"])
    diff_pct = abs(active_with_horizon - expected) / expected * 100.0 if expected else None
    max_year_share = None
    if active_with_horizon:
        max_year_share = max(year_counts.values()) / active_with_horizon if year_counts else None
    return {
        "active_rows_rule_only": active_rows,
        "active_event_count_with_horizon": active_with_horizon,
        "missing_horizon_count": missing_horizon,
        "expected_stage64r_candidate_active_days": expected,
        "difference_pct_vs_expected": diff_pct,
        "within_tolerance": diff_pct is not None and diff_pct <= float(cfg["reconstruction_tolerance_pct"]),
        "first_active_feature_date": first_active,
        "last_active_feature_date": last_active,
        "mean_return_bps": mean(returns),
        "std_return_bps": stddev(returns),
        "positive_event_share": (sum(1 for x in returns if x > 0) / len(returns)) if returns else None,
        "min_return_bps": min(returns) if returns else None,
        "max_return_bps": max(returns) if returns else None,
        "max_year_share": max_year_share,
        "year_counts": dict(sorted(year_counts.items())),
        "failed_condition_counts_top": dict(sorted(failed_condition_counts.items(), key=lambda kv: kv[1], reverse=True)[:20]),
    }


def _build_variants(base_rule: Dict[str, Any], cfg: Dict[str, Any]) -> List[Dict[str, Any]]:
    variants: List[Dict[str, Any]] = []
    variants.append({
        "variant_id": "v1_current_locked_rule",
        "extra_conditions": [],
        "hypothesis": "Current locked rule exactly as Stage66 Package 1 used it.",
    })

    extras = cfg.get("candidate_extra_conditions", [])
    max_extra = int(cfg.get("max_extra_conditions_per_variant", 2))
    # Single-condition variants first, then small combinations. This is diagnostic, not open-ended search.
    for k in range(1, max_extra + 1):
        for combo in itertools.combinations(extras, k):
            variant_id = "v1_plus_" + "__".join([str(c["field"]) for c in combo])
            variants.append({
                "variant_id": variant_id,
                "extra_conditions": [copy.deepcopy(c) for c in combo],
                "hypothesis": "Pre-registered diagnostic check: Stage64R may have included this condition set.",
            })
    return variants


def _write_proposed_files(
    root: Path,
    out_dir: Path,
    cfg: Dict[str, Any],
    base_rule: Dict[str, Any],
    matched_variant: Dict[str, Any],
    result: Dict[str, Any],
) -> Dict[str, Any]:
    proposed_rule = _make_rule_variant(base_rule, "v2_stage66a2_reconciled_proposed", matched_variant["extra_conditions"])
    proposed_rule["rule_lock_payload"]["locked_from"] = {
        "stage": "Stage66A2 reconstruction reconciliation",
        "reason": "Unique pre-registered variant matched Stage64R candidate_active_days within tolerance.",
        "matched_variant_id": matched_variant["variant_id"],
        "expected_stage64r_candidate_active_days": cfg["expected_stage64r_candidate_active_days"],
        "matched_active_event_count_with_horizon": result["active_event_count_with_horizon"],
        "difference_pct_vs_expected": result["difference_pct_vs_expected"],
        "created_utc": _iso_now(),
    }
    proposed_rule["rule_sha256"] = canonical_sha256(proposed_rule["rule_lock_payload"])

    proposed_rule_repo_path = cfg.get("proposed_locked_rule_path", "configs/h64l_locked_rule_v2_stage66a2_proposed.json")
    proposed_cfg_repo_path = cfg.get("proposed_stage66a_config_path", "configs/stage66a_h64l_concentration_audit_reconciled_v2.json")

    proposed_rule_abs = root / proposed_rule_repo_path
    write_json(proposed_rule_abs, proposed_rule)

    # Build a rerun config by copying current Stage66A config and changing the locked rule path.
    stage66a_cfg_path = root / cfg.get("stage66a_config_path", "configs/stage66a_h64l_concentration_audit.json")
    stage66a_cfg = read_json(stage66a_cfg_path)
    stage66a_cfg["locked_rule_path"] = proposed_rule_repo_path
    stage66a_cfg["reconciliation_source"] = {
        "stage": "Stage66A2",
        "matched_variant_id": matched_variant["variant_id"],
        "note": "Generated automatically only because exactly one variant matched Stage64R within locked tolerance.",
    }
    proposed_cfg_abs = root / proposed_cfg_repo_path
    write_json(proposed_cfg_abs, stage66a_cfg)

    rerun_commands = f"""cd {root}\n\npython3 app/stage66a_h64l_concentration_audit.py \\\n  --root . \\\n  --config {proposed_cfg_repo_path} \\\n  --out reports/stage66a_h64l_concentration_audit_reconciled_v2 \\\n  --write-events\n\npython3 app/stage66f_governance_dashboard.py \\\n  --root . \\\n  --out reports/stage66f_governance_dashboard\n"""
    (out_dir / "stage66a2_rerun_commands.txt").write_text(rerun_commands, encoding="utf-8")

    return {
        "proposed_locked_rule_path": proposed_rule_repo_path,
        "proposed_stage66a_config_path": proposed_cfg_repo_path,
        "proposed_rule_sha256": proposed_rule["rule_sha256"],
        "rerun_commands_path": str(out_dir / "stage66a2_rerun_commands.txt"),
    }


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--root", default=".")
    p.add_argument("--config", default="configs/stage66a2_h64l_reconstruction_reconciler.json")
    p.add_argument("--out", default="reports/stage66a2_h64l_reconstruction_reconciler")
    args = p.parse_args()

    root = Path(args.root).resolve()
    cfg = read_json(root / args.config)
    out_dir = Path(args.out) if Path(args.out).is_absolute() else root / args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    base_rule = load_locked_rule(root / cfg["base_locked_rule_path"])
    macro_rows, external_series = _read_rows(root, cfg)
    variants = _build_variants(base_rule, cfg)

    variant_results: List[Dict[str, Any]] = []
    for v in variants:
        rule = _make_rule_variant(base_rule, v["variant_id"], v["extra_conditions"])
        stats = _event_stats_for_rule(macro_rows, external_series, rule, cfg)
        variant_results.append({
            "variant_id": v["variant_id"],
            "hypothesis": v["hypothesis"],
            "extra_conditions": v["extra_conditions"],
            "condition_count": len(rule["rule_lock_payload"].get("conditions", [])),
            "rule_sha256": rule["rule_sha256"],
            **stats,
        })

    variant_results.sort(key=lambda x: (abs(float(x["difference_pct_vs_expected"])) if x.get("difference_pct_vs_expected") is not None else 10**9, x["condition_count"]))
    matches = [r for r in variant_results if r.get("within_tolerance")]

    output_artifacts: Dict[str, Any] = {}
    decision = "NO_UNIQUE_RECONCILIATION_MATCH_DO_NOT_CHANGE_RULE_LOCK"
    status = "STAGE66A2_COMPLETE_NEEDS_REVIEW_NO_PROMOTION"
    if len(matches) == 1 and bool(cfg.get("write_proposed_rule_if_unique_match", True)):
        matched_id = matches[0]["variant_id"]
        matched_variant = next(v for v in variants if v["variant_id"] == matched_id)
        output_artifacts = _write_proposed_files(root, out_dir, cfg, base_rule, matched_variant, matches[0])
        decision = "UNIQUE_RECONCILIATION_MATCH_WRITE_PROPOSED_RULE_LOCK_V2_NO_PROMOTION"
        status = "STAGE66A2_PROPOSED_RULE_LOCK_WRITTEN_NO_PROMOTION"
    elif len(matches) > 1:
        decision = "MULTIPLE_RECONCILIATION_MATCHES_REQUIRE_MANUAL_RULE_LOCK_REVIEW"
    else:
        decision = "NO_RECONCILIATION_MATCH_REQUIRES_STAGE64R_SOURCE_AUDIT"

    summary = {
        "stage": "Stage66A2_H64L_RECONSTRUCTION_RECONCILER",
        "generated_utc": _iso_now(),
        "root": str(root),
        "status": status,
        "decision": decision,
        "hard_blocks": [
            "NO_PAPER_ORDER",
            "NO_EA_PROMOTION",
            "NO_PAPER_LIVE",
            "NO_LIVE",
            "NO_BROKER_CONNECTION",
            "NO_THRESHOLD_TUNING",
            "NO_RESCUE_FILTERING",
            "NO_PROMOTION_FROM_RECONCILIATION_ONLY",
        ],
        "expected_stage64r_candidate_active_days": cfg["expected_stage64r_candidate_active_days"],
        "reconstruction_tolerance_pct": cfg["reconstruction_tolerance_pct"],
        "base_locked_rule_path": cfg["base_locked_rule_path"],
        "base_rule_sha256": base_rule["rule_sha256"],
        "variant_count": len(variant_results),
        "match_count": len(matches),
        "matches": matches,
        "top_ranked_variants": variant_results[: int(cfg.get("top_n_variants_in_summary", 20))],
        "output_artifacts": output_artifacts,
        "next_step": (
            "If decision is UNIQUE_RECONCILIATION_MATCH_WRITE_PROPOSED_RULE_LOCK_V2_NO_PROMOTION, rerun Stage66A with the generated reconciled config and then rerun Stage66F. Otherwise inspect top variants and Stage64R source artifacts before changing any rule."
        ),
    }

    write_json(out_dir / "stage66a2_h64l_reconstruction_reconciler_summary.json", summary)
    write_json(out_dir / "stage66a2_h64l_reconstruction_variant_matrix.json", variant_results)
    sections = [
        ("Decision", f"- status: `{status}`\n- decision: `{decision}`\n- match_count: `{len(matches)}`"),
        ("Matched variants", json.dumps(matches, ensure_ascii=False, indent=2)),
        ("Top ranked variants", json.dumps(variant_results[: int(cfg.get("top_n_variants_in_summary", 20))], ensure_ascii=False, indent=2)),
        ("Output artifacts", json.dumps(output_artifacts, ensure_ascii=False, indent=2)),
        ("Hard blocks", "\n".join([f"- `{x}`" for x in summary["hard_blocks"]])),
    ]
    write_report(out_dir / "stage66a2_h64l_reconstruction_reconciler_report.md", "Stage66A2 H64L Reconstruction Reconciler", sections)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
