from __future__ import annotations

import argparse
import glob
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd
import yaml

from app.xauusd_stage2j_candidate_analysis import (
    load_json,
    make_trades,
    metrics,
    parse_variant,
    read_db_interval,
)


def load_yaml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def latest_file(pattern: str) -> Optional[Path]:
    files = sorted(glob.glob(pattern), key=lambda p: Path(p).stat().st_mtime, reverse=True)
    return Path(files[0]) if files else None


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2, sort_keys=True)
    tmp.replace(path)


def fold_metrics(trades: pd.DataFrame, fold_count: int) -> Dict[str, Any]:
    work = trades.sort_values("entry_time_utc").reset_index(drop=True)
    n = len(work)
    if n == 0:
        return {"folds": [], "positive_fold_count": 0, "positive_fold_ratio": 0.0}

    fold_count = max(1, int(fold_count))
    indices = np.array_split(np.arange(n), fold_count)

    rows = []
    for i, idx in enumerate(indices, start=1):
        g = work.iloc[idx]
        m = metrics(g["net_usd"].to_numpy(dtype=float))
        m["fold"] = i
        m["start_time_utc"] = str(g["entry_time_utc"].iloc[0]) if not g.empty else None
        m["end_time_utc"] = str(g["entry_time_utc"].iloc[-1]) if not g.empty else None
        rows.append(m)

    positive = [r for r in rows if float(r.get("total_net_usd", 0.0)) > 0]
    return {
        "folds": rows,
        "positive_fold_count": int(len(positive)),
        "fold_count": int(len(rows)),
        "positive_fold_ratio": float(len(positive) / max(len(rows), 1)),
        "last_fold": rows[-1] if rows else {},
        "worst_fold": min(rows, key=lambda r: float(r.get("total_net_usd", 0.0))) if rows else {},
        "best_fold": max(rows, key=lambda r: float(r.get("total_net_usd", 0.0))) if rows else {},
    }


def rolling_metrics(trades: pd.DataFrame, window: int) -> Dict[str, Any]:
    work = trades.sort_values("entry_time_utc").reset_index(drop=True)
    values = work["net_usd"].to_numpy(dtype=float)
    window = int(window)

    if values.size < window or window <= 1:
        return {
            "window_trades": window,
            "window_count": 0,
            "negative_window_count": 0,
            "negative_window_ratio": 0.0,
            "worst_window_total_net_usd": None,
            "best_window_total_net_usd": None,
        }

    sums = np.convolve(values, np.ones(window), mode="valid")
    return {
        "window_trades": window,
        "window_count": int(sums.size),
        "negative_window_count": int(np.sum(sums < 0)),
        "negative_window_ratio": float(np.mean(sums < 0)),
        "worst_window_total_net_usd": float(np.min(sums)),
        "best_window_total_net_usd": float(np.max(sums)),
    }


def direction_metrics(trades: pd.DataFrame) -> Dict[str, Any]:
    out = {}
    for direction, g in trades.groupby("direction_label", sort=True):
        out[str(direction)] = metrics(g["net_usd"].to_numpy(dtype=float))
    return out


def tail_metrics(trades: pd.DataFrame, n: int) -> Dict[str, Any]:
    work = trades.sort_values("entry_time_utc").tail(int(n))
    return metrics(work["net_usd"].to_numpy(dtype=float))


def cost_multiplier_metrics(trades: pd.DataFrame, multiplier: float) -> Dict[str, Any]:
    raw = trades["raw_usd"].to_numpy(dtype=float)
    cost = trades["cost_usd"].to_numpy(dtype=float)
    return metrics(raw - cost * float(multiplier))


def analyze_candidate(
    candidate: Dict[str, Any],
    db_path: str,
    cfg: Dict[str, Any],
    data_cache: Dict[str, pd.DataFrame],
) -> Dict[str, Any]:
    family = candidate["family"]
    variant = candidate["variant"]
    params = parse_variant(family, variant)
    interval = params["interval"]

    if interval not in data_cache:
        data_cache[interval] = read_db_interval(db_path, interval)

    stage2j_base = candidate.get("base", {})
    cost_usd = float(candidate.get("cost_usd") or 0.35)
    # Stage 2J summary does not store cost directly per candidate; infer from prior stage if absent.
    if "cost_model" in candidate:
        cost_usd = float(candidate["cost_model"].get("effective_roundtrip_cost_usd", cost_usd))

    # Stable candidates generated by Stage 2J used stage2d_summary cost. If not present here, 0.35 is the project default.
    trades = make_trades(data_cache[interval], family, variant, params, cost_usd=cost_usd)
    if trades.empty:
        return {
            "family": family,
            "variant": variant,
            "walkforward_pass": False,
            "reason": "no_trades",
        }

    folds_cfg = cfg.get("folds", {}) or {}
    rolling_cfg = cfg.get("rolling", {}) or {}
    decision_cfg = cfg.get("decision", {}) or {}

    folds = fold_metrics(trades, fold_count=int(folds_cfg.get("count", 5)))
    rolling = rolling_metrics(trades, window=int(rolling_cfg.get("window_trades", 25)))
    directions = direction_metrics(trades)
    last50 = tail_metrics(trades, 50)
    last100 = tail_metrics(trades, 100)
    cost_x4 = cost_multiplier_metrics(trades, 4.0)
    base = metrics(trades["net_usd"].to_numpy(dtype=float))

    long_total = float(directions.get("long", {}).get("total_net_usd", 0.0))
    short_total = float(directions.get("short", {}).get("total_net_usd", 0.0))
    both_negative = long_total < 0 and short_total < 0

    checks = {
        "min_trades_per_fold": all(int(f.get("trade_count", 0)) >= int(folds_cfg.get("min_trades_per_fold", 20)) for f in folds.get("folds", [])),
        "positive_fold_ratio": float(folds.get("positive_fold_ratio", 0.0)) >= float(folds_cfg.get("min_positive_fold_ratio", 0.60)),
        "last_fold_positive": (not bool(folds_cfg.get("require_last_fold_positive", True))) or float(folds.get("last_fold", {}).get("total_net_usd", 0.0)) > 0,
        "rolling_negative_window_ratio": float(rolling.get("negative_window_ratio", 1.0)) <= float(rolling_cfg.get("max_negative_window_ratio", 0.45)),
        "cost_x4_positive": (not bool(decision_cfg.get("require_cost_x4_positive", True))) or float(cost_x4.get("total_net_usd", 0.0)) > 0,
        "long_short_not_both_negative": (not bool(decision_cfg.get("require_long_short_not_both_negative", True))) or not both_negative,
        "last_50_positive": (not bool(decision_cfg.get("require_last_50_positive", True))) or float(last50.get("total_net_usd", 0.0)) > 0,
        "last_100_positive": (not bool(decision_cfg.get("require_last_100_positive", False))) or float(last100.get("total_net_usd", 0.0)) > 0,
    }

    passed = all(checks.values())
    reason = "walkforward_pass" if passed else "failed_checks:" + ",".join(k for k, v in checks.items() if not v)

    return {
        "family": family,
        "variant": variant,
        "walkforward_pass": bool(passed),
        "reason": reason,
        "checks": checks,
        "base": base,
        "folds": folds,
        "rolling": rolling,
        "direction": directions,
        "last_50": last50,
        "last_100": last100,
        "cost_x4": cost_x4,
    }


def write_markdown(path: Path, payload: Dict[str, Any]) -> None:
    lines = []
    lines.append("# XAUUSD Stage 2K Walk-Forward Validation")
    lines.append("")
    lines.append(f"- Generated at UTC: `{payload['generated_at_utc']}`")
    lines.append(f"- Decision: `{payload['decision']['status']}`")
    lines.append(f"- Reason: `{payload['decision']['reason']}`")
    lines.append(f"- Candidates analyzed: `{payload['candidate_count']}`")
    lines.append("")
    lines.append("| Family | Variant | Pass | Reason | Trades | Total net | PF | Fold +ratio | Last fold | Worst rolling 25 | Last 50 | Cost x4 |")
    lines.append("|---|---|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|")
    for row in payload["analyses"]:
        base = row.get("base", {})
        folds = row.get("folds", {})
        rolling = row.get("rolling", {})
        last50 = row.get("last_50", {})
        costx4 = row.get("cost_x4", {})
        pf = base.get("profit_factor")
        lines.append(
            "| {family} | {variant} | {passed} | {reason} | {trades} | {total:.4f} | {pf} | {fold_ratio:.2f} | {last_fold:.4f} | {worst_roll} | {last50:.4f} | {costx4:.4f} |".format(
                family=row.get("family"),
                variant=row.get("variant"),
                passed=row.get("walkforward_pass"),
                reason=row.get("reason"),
                trades=int(base.get("trade_count", 0)),
                total=float(base.get("total_net_usd", 0.0)),
                pf="n/a" if pf is None else f"{float(pf):.3f}",
                fold_ratio=float(folds.get("positive_fold_ratio", 0.0)),
                last_fold=float(folds.get("last_fold", {}).get("total_net_usd", 0.0)),
                worst_roll="n/a" if rolling.get("worst_window_total_net_usd") is None else f"{float(rolling.get('worst_window_total_net_usd')):.4f}",
                last50=float(last50.get("total_net_usd", 0.0)),
                costx4=float(costx4.get("total_net_usd", 0.0)),
            )
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Stage 2K walk-forward validation for Stage 2J stable candidates.")
    parser.add_argument("--config", default="configs/stage2k.yaml")
    parser.add_argument("--stage2j-summary", default=None)
    parser.add_argument("--data-db", default=None)
    parser.add_argument("--report-dir", default=None)
    args = parser.parse_args()

    cfg = load_yaml(Path(args.config))
    db_path = args.data_db or cfg.get("data_db", "data/store/xauusd.sqlite")
    report_dir = Path(args.report_dir or cfg.get("report_dir", "data/reports"))
    report_dir.mkdir(parents=True, exist_ok=True)

    summary_path = Path(args.stage2j_summary) if args.stage2j_summary else latest_file(cfg.get("stage2j_summary_glob", "data/reports/stage2j_candidate_stability_summary_*.json"))
    if not summary_path or not summary_path.exists():
        raise SystemExit("Stage 2J summary not found. Run Stage 2J first.")

    stage2j = load_json(summary_path)
    candidates = list(stage2j.get("stable_candidates", []))
    max_candidates = int((cfg.get("selection", {}) or {}).get("max_candidates", 5))
    candidates = candidates[:max_candidates]

    data_cache: Dict[str, pd.DataFrame] = {}
    analyses = [analyze_candidate(c, db_path=db_path, cfg=cfg, data_cache=data_cache) for c in candidates]

    passed = [x for x in analyses if x.get("walkforward_pass")]
    if passed:
        status = "stage2k_walkforward_pass_found"
        reason = "At least one stable candidate passed rolling/fold/tail/cost diagnostics."
    else:
        status = "no_stage2k_walkforward_pass"
        reason = "No stable candidate passed Stage 2K walk-forward diagnostics."

    stamp = utc_stamp()
    summary_json = report_dir / f"stage2k_walkforward_summary_{stamp}.json"
    summary_md = report_dir / f"stage2k_walkforward_summary_{stamp}.md"

    payload = {
        "ok": True,
        "stage": "stage2k_walkforward_validation",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "data_db": db_path,
        "stage2j_summary": str(summary_path),
        "candidate_count": int(len(candidates)),
        "decision_config": {
            "folds": cfg.get("folds", {}),
            "rolling": cfg.get("rolling", {}),
            "decision": cfg.get("decision", {}),
        },
        "decision": {
            "status": status,
            "reason": reason,
            "walkforward_pass_count": int(len(passed)),
        },
        "passed_candidates": passed,
        "analyses": analyses,
    }

    write_json(summary_json, payload)
    write_markdown(summary_md, payload)

    print(
        json.dumps(
            {
                "ok": True,
                "decision": payload["decision"],
                "summary_json": str(summary_json),
                "summary_md": str(summary_md),
                "candidate_count": len(candidates),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
